#!/bin/bash
echo
## Compile the smart contracts
yarn run compile
## Add to the commit the new artifacts
cp artifacts/contracts/hermez/Hermez.sol/Hermez.json compiled-contracts/
cp artifacts/contracts/hermez/lib/InstantWithdrawManager.sol/InstantWithdrawManager.json compiled-contracts/
cp artifacts/contracts/hermez/lib/HermezHelpers.sol/HermezHelpers.json compiled-contracts/
cp artifacts/contracts/auction/HermezAuctionProtocol.sol/HermezAuctionProtocol.json compiled-contracts/
cp artifacts/contracts/withdrawalDelayer/WithdrawalDelayer.sol/WithdrawalDelayer.json compiled-contracts/
git add compiled-contracts

exit