#!/bin/bash
echo
## Compile the smart contracts
yarn run compile
## Add to the commit the new artifacts
git add -u artifacts/contracts/hermez/Hermez.sol/Hermez.json
git add -u artifacts/contracts/hermez/lib/InstantWithdrawManager.sol/InstantWithdrawManager.json
git add -u artifacts/contracts/hermez/lib/HermezHelpers.sol/HermezHelpers.json
git add -u artifacts/contracts/auction/HermezAuctionProtocol.sol/HermezAuctionProtocol.json
git add -u artifacts/contracts/withdrawalDelayer/WithdrawalDelayer.sol/WithdrawalDelayer.json

exit