name: Python check ABI

on: 
   push:
      branches: [ feature/abi ]
  
jobs:
    abi:
      name: check abi
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
          architecture: 'x64' 
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - run: npm install
      - run: ./scripts/getABI.py 1
